#+TITLE:  Zsh Fabric Fabfile
#+AUTHOR: Xavier Garrido
#+DATE:   2013-02-17
#+OPTIONS: toc:nil num:nil ^:nil

This is part of the [[file:zsh-fabric.org][Zsh Fabric]].

* Zsh Fabric - Fabfile
This file sets all the =python= functions to be used by Fabric and the
[[file:zsh-fabric.org][=fab_manager=]] function.

** Import fabric API
#+BEGIN_SRC python
  from fabric.api import *
#+END_SRC

** Zsh shebang
Since most of the actions done through Fabric will used =zsh= functions, we will
need to source the =.zshrc= file on the remote machines[1]. This simple file
will be placed in =/tmp/${USER}= directory.

#+BEGIN_SRC python
  SHEBANGDIR  = '/tmp/${USER}'
  SHEBANGFILE = SHEBANGDIR + '/.zshfab.zsh'
  SHEBANGCMD  = 'source ~/.zshrc > /dev/null 2>&1'

  def create_shebang (CMD=''):
      run ("mkdir -p %s" % SHEBANGDIR)
      if CMD:
          run ("echo \"%s && %s && $\"@\"\" > %s" % (SHEBANGCMD, CMD, SHEBANGFILE))
      else:
          run ("echo \"%s && $\"@\"\" > %s" % (SHEBANGCMD, SHEBANGFILE))
#+END_SRC

** Fabric operations
*** Needed =hello= task
#+BEGIN_SRC python
  def hello (msg="Hello World!"):
      run ('echo %s' % msg)
#+END_SRC

*** Install debian packages
This function will install in *parallel* several debian packages

#+BEGIN_SRC python
  def install_debian (packages):
      sudo ("apt-get -y install %s" % packages)
#+END_SRC

*** Update debian machines
This function will run =apt-get= commands in *parallel* to update and installed
new packages version.

#+BEGIN_SRC python
  def update_debian ():
      sudo ("apt-get -y update")
      sudo ("apt-get -y upgrade")
      sudo ("apt-get -y dist-upgrade")
      sudo ("apt-get -y autoremove")
#+END_SRC

*** Update =.zshrc= file
#+BEGIN_SRC python
  def update_zshrc ():
      run ("wget --no-check-certificate https://raw.github.com/xgarrido/dotfiles/master/zshrc -O ~/.zshrc")
#+END_SRC

*** Update =antigen= repositories
[[https://github.com/zsh-users/antigen][Antigen]] is a plugin manager for =zsh=. The =antigen= function can do all the
=antigen= actions (update, cleanup...) by passing the action as a argument. By
default, this function update all the repositories.

#+BEGIN_SRC python
  def antigen (CMD="update"):
      create_shebang ()
      run ("zsh %s antigen %s" % (SHEBANGFILE, CMD))
  def update_antigen ():
      antigen ("selfupdate")
      antigen ()
#+END_SRC

*** Update SuperNEMO software
**** Aggregators
[[https://github.com/xgarrido/zsh-aggregator][Aggregators]] are tools provided by SuperNEMO collaboration to ease the
installation of all SuperNEMO software components.
#+BEGIN_SRC python
  def aggregator (CMD="update all"):
      create_shebang ()
      run ("zsh %s aggregator %s" % (SHEBANGFILE, CMD))
  def update_aggregator ():
      aggregator ("checkout all")
      aggregator ("update all")

  def build_aggregator ():
      update_aggregator ()
      aggregator ("build all")
#+END_SRC

**** SN@ilWare
[[https://github.com/xgarrido/zsh-snailware][SN@ilWare]] is a tool to manage a local installation of all SuperNEMO software
components. It does not rely to aggregators and works almost alone.
#+BEGIN_SRC python
  def snailware (CMD="status"):
      run ("zsh %s snailware %s" % (SHEBANGFILE, CMD))
  def update_snailware (component='all'):
      create_shebang ()
      snailware ("git-update %s" % component)

  def configure_snailware (component='all', options=''):
      create_shebang ("aggregator setup cadfael && snailware setup %s" % component)
      snailware ("configure %s %s" % (options, component))

  def build_snailware (component='all'):
      create_shebang ("aggregator setup cadfael && snailware setup %s" % component)
      snailware ("build %s" % component)

  def test_snailware (component='all'):
      create_shebang ("aggregator setup cadfael && snailware setup %s" % component)
      snailware ("test %s" % component)
#+END_SRC

*** Generic commands
**** Zsh function call
#+BEGIN_SRC python
  def zsh_command (cmd):
      create_shebang ()
      run ("zsh %s %s" % (SHEBANGFILE, CMD))
#+END_SRC
**** Bash commands
#+BEGIN_SRC python
  def command (cmd):
      run (cmd)
#+END_SRC
**** =sudo= commands
#+BEGIN_SRC python
  def sudo_command (cmd):
      sudo (cmd)
#+END_SRC

*** Miscellaneous
**** Play a song
#+BEGIN_SRC python
  def play_song (name="foley"):
      sudo_command ("modprobe pcspkr")
      if name == 'foley':
          song = "beep " + \
                 "-f 659 -l 460 -n -f 784  -l 340 -n -f 659  -l 230 -n " + \
                 "-f 659 -l 110 -n -f 880  -l 230 -n -f 659  -l 230 -n " + \
                 "-f 587 -l 230 -n -f 659  -l 460 -n -f 988  -l 340 -n " + \
                 "-f 659 -l 230 -n -f 659  -l 110 -n -f 1047 -l 230 -n " + \
                 "-f 988 -l 230 -n -f 784  -l 230 -n -f 659  -l 230 -n " + \
                 "-f 988 -l 230 -n -f 1318 -l 230 -n -f 659  -l 110 -n " + \
                 "-f 587 -l 230 -n -f 587  -l 110 -n -f 494  -l 230 -n " + \
                 "-f 740 -l 230 -n -f 659 -l 460"
      elif name == 'mario':
          song = "beep -f 330 -l 137 -n -f 330 -l 275 -n -f 330 -l 137 -d 137 -n -f 262 -l 137 -n -f 330 -l 275 -n -f 392 -l 550 -d 550 -n -f 262 -l 412 -n -f 196 -l 137 -d 275 -n -f 164 -l 137 -d 137 -n -f 220 -l 275 -n -f 247 -l 137 -d 137 -n -f 233 -l 137 -n -f 220 -l 275 -n -f 196 -l 205 -n -f 330 -l 205 -n -f 392 -l 275 -n -f 440 -l 275 -n -f 349 -l 137 -n -f 392 -l 137 -d 137 -n -f 330 -l 275 -n -f 262 -l 137 -n -f 294 -l 137 -n -f 247 -l 412 -n -f 262 -l 412 -n -f 196 -l 137 -d 275 -n -f 164 -l 275 -d 137 -n -f 220 -l 275 -n -f 247 -l 137 -d 137 -n -f 233 -l 137 -n -f 220 -l 275 -n -f 196 -l 205 -n -f 330 -l 205 -n -f 392 -l 275 -n -f 440 -l 275 -n -f 349 -l 137 -n -f 392 -l 137 -d 137 -n -f 330 -l 275 -n -f 262 -l 137 -n -f 294 -l 137 -n -f 247 -l 412 -d 275 -n -f 392 -l 137 -n -f 370 -l 137 -n -f 349 -l 137 -n -f 311 -l 275 -n -f 330 -l 137 -d 137 -n -f 207 -l 137 -n -f 220 -l 137 -n -f 262 -l 137 -d 137 -n -f 220 -l 137 -n -f 262 -l 137 -n -f 294 -l 137 -d 275 -n -f 392 -l 137 -n -f 370 -l 137 -n -f 349 -l 137 -n -f 311 -l 275 -n -f 330 -l 137 -d 137 -n -f 523 -l 275 -n -f 523 -l 137 -n -f 523 -l 550 -n -f 392 -l 137 -n -f 370 -l 137 -n -f 349 -l 137 -n -f 311 -l 275 -n -f 330 -l 137 -d 137 -n -f 207 -l 137 -n -f 220 -l 137 -n -f 262 -l 137 -d 137 -n -f 220 -l 137 -n -f 262 -l 137 -n -f 294 -l 137 -d 275 -n -f 311 -l 275 -d 137 -n -f 294 -l 275 -n -f 262 -l 550 -d 550"
      elif name == 'elise':
          song = "beep -f 659 120 -n -f 622 120 -n -f 659 120 -n -f 622 120 -n -f 659 120 -n -f 94 120 -n -f 587 120 -n -f 523 120 -n -f 440 120 -n -f 262 120 -n -f 330 120 -n -f 440 120 -n -f 494 120 -n -f 330 120 -n -f 415 120 -n -f 494 120 -n -f 523 120 -n -f 330 120 -n -f 659 120 -n -f 622 120 -n -f 659 120 -n -f 622 120 -n -f 659 120 -n -f 494 120 -n -f 587 120 -n -f 523 120 -n -f 440 120 -n -f 262 120 -n -f 330 120 -n -f 440 120 -n -f 494 120 -n -f 330 120 -n -f 523 120 -n -f 494 120 -n -f 440 120"
      elif name == 'alle':
          song = "beep -f 261 -n -f 294 -n -f 330 -n -f 349 -n -f 392 -l 400 -n -f 392 -l 400 -n -f 440 -n -f 440 -n -f 440 -n -f 440 -n -f 392 -l 800 -n -f 440 -n -f 440 -n -f 440 -n -f 440 -n -f 392 -l 800 -n -f 349 -n -f 349 -n -f 349 -n -f 349 -n -f 330 -l 400 -n -f 330 -l 400 -n -f 294 -n -f 294 -n -f 294 -n -f 294 -n -f 261 -l 800"
      elif name == 'happy_new_year':
          song = "beep -f261 -l500 -n -f349 -l500 -n -f349 -l250 -n -f392 -l250 -n -f349 -l250 -n -f329 -l250 -n -f293 -l500 -n -f293 -l500 -n -f293 -l500 -n -f392 -l500 -n -f392 -l250 -n -f440 -l250 -n -f392 -l250 -n -f349 -l250 -n -f329 -l500 -n -f329 -l500 -n -f329 -l500 -n -f440 -l500 -n -f440 -l250 -n -f493 -l250 -n -f440 -l250 -n -f392 -l250 -n -f349 -l500 -n -f293 -l500 -n -f261 -l250 -n -f261 -l250 -n -f293 -l500 -n -f392 -l500 -n -f329 -l500 -n -f349 -l1000 -n -f261 -l500 -n -f349 -l500 -n -f349 -l500 -n -f349 -l500 -n -f329 -l1000 -n -f329 -l500 -n -f349 -l500 -n -f329 -l500 -n -f293 -l500 -n -f261 -l1000 -n -f392 -l1000 -n -f440 -l500 -n -f392 -l250 -n -f392 -l250 -n -f349 -l250 -n -f349 -l250 -n -f523 -l500 -n -f261 -l500 -n -f261 -l250 -n -f261 -l250 -n -f293 -l500 -n -f392 -l500 -n -f329 -l500 -n -f349 -l1000"
      elif name == 'starwars':
          song = "beep -l 350 -f 392 -D 100 --new -l 350 -f 392 -D 100 --new -l 350 -f 392 -D 100 --new -l 250 -f 311.1 -D 100 --new -l 25 -f 466.2 -D 100 --new -l 350 -f 392 -D 100 --new -l 250 -f 311.1 -D 100 --new -l 25 -f 466.2 -D 100 --new -l 700 -f 392 -D 100 --new -l 350 -f 587.32 -D 100 --new -l 350 -f 587.32 -D 100 --new -l 350 -f 587.32 -D 100 --new -l 250 -f 622.26 -D 100 --new -l 25 -f 466.2 -D 100 --new -l 350 -f 369.99 -D 100 --new -l 250 -f 311.1 -D 100 --new -l 25 -f 466.2 -D 100 --new -l 700 -f 392 -D 100 --new -l 350 -f 784 -D 100 --new -l 250 -f 392 -D 100 --new -l 25 -f 392 -D 100 --new -l 350 -f 784 -D 100 --new -l 250 -f 739.98 -D 100 --new -l 25 -f 698.46 -D 100 --new -l 25 -f 659.26 -D 100 --new -l 25 -f 622.26 -D 100 --new -l 50 -f 659.26 -D 400 --new -l 25 -f 415.3 -D 200 --new -l 350 -f 554.36 -D 100 --new -l 250 -f 523.25 -D 100 --new -l 25 -f 493.88 -D 100 --new -l 25 -f 466.16 -D 100 --new -l 25 -f 440 -D 100 --new -l 50 -f 466.16 -D 400 --new -l 25 -f 311.13 -D 200 --new -l 350 -f 369.99 -D 100 --new -l 250 -f 311.13 -D 100 --new -l 25 -f 392 -D 100 --new -l 350 -f 466.16 -D 100 --new -l 250 -f 392 -D 100 --new -l 25 -f 466.16 -D 100 --new -l 700 -f 587.32 -D 100 --new -l 350 -f 784 -D 100 --new -l 250 -f 392 -D 100 --new -l 25 -f 392 -D 100 --new -l 350 -f 784 -D 100 --new -l 250 -f 739.98 -D 100 --new -l 25 -f 698.46 -D 100 --new -l 25 -f 659.26 -D 100 --new -l 25 -f 622.26 -D 100 --new -l 50 -f 659.26 -D 400 --new -l 25 -f 415.3 -D 200 --new -l 350 -f 554.36 -D 100 --new -l 250 -f 523.25 -D 100 --new -l 25 -f 493.88 -D 100 --new -l 25 -f 466.16 -D 100 --new -l 25 -f 440 -D 100 --new -l 50 -f 466.16 -D 400 --new -l 25 -f 311.13 -D 200 --new -l 350 -f 392 -D 100 --new -l 250 -f 311.13 -D 100 --new -l 25 -f 466.16 -D 100 --new -l 300 -f 392.00 -D 150 --new -l 250 -f 311.13 -D 100 --new -l 25 -f 466.16 -D 100 --new -l 700 -f 392"

      sudo_command (song)
#+END_SRC

* Footnotes

[1] this assumes that all the machines are configured and setup in the same way.
